pipeline {
  agent any

  tools {
    jdk 'Java-17'
    maven 'Maven-3.9.8'
  }

  stages {
    stage('Clean and Validate Maven App') {
      steps{
        sh 'mvn clean validate'
      }
    }

    stage('Static Code Analysis'){
      steps{
        withSonarQubeEnv('sonarqube-server'){
          sh 'mvn package sonar:sonar -Dsonar.projectKey=bin-project-org_bin-project -Dsonar.organization=bin-project-org -Dsonar.projectName=bin_project -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=5a1695356b859106f3f8a7f -X'
        }
      }
    }
  }
}